export const Router_UI_CommonAttrs = 'pages/ui/UI_CommonAttrs'

export const Router_UI_CommonEvents = 'pages/ui/UI_CommonEvents'

export const Router_UI_Button = 'pages/ui/UI_Button'

export const Router_UI_CheckBox = 'pages/ui/UI_CheckBox'

export const Router_UI_DatePicker = 'pages/ui/UI_DatePicker'

export const Router_UI_Divider = 'pages/ui/UI_Divider'

export const Router_UI_Flex = 'pages/ui/UI_Flex'

export const Router_UI_GridRowGridCol = 'pages/ui/UI_GridRowGridCol'

export const Router_UI_Image = 'pages/ui/UI_Image'

export const Router_UI_Marquee = 'pages/ui/UI_Marquee'

export const Router_UI_Menu = 'pages/ui/UI_Menu'

export const Router_UI_Progress = 'pages/ui/UI_Progress'

export const Router_UI_QRCode = 'pages/ui/UI_QRCode'

export const Router_UI_Rating = 'pages/ui/UI_Rating'

export const Router_UI_RelativeContainer = 'pages/ui/UI_RelativeContainer'

export const Router_UI_RowColumn = 'pages/ui/UI_RowColumn'

export const Router_UI_Search = 'pages/ui/UI_Search'

export const Router_UI_Slider = 'pages/ui/UI_Slider'

export const Router_UI_Stack = 'pages/ui/UI_Stack'

export const Router_UI_Stepper = 'pages/ui/UI_Stepper'

export const Router_UI_Text = 'pages/ui/UI_Text'

export const Router_UI_TextClock = 'pages/ui/UI_TextClock'

export const Router_UI_TextInput_Area = 'pages/ui/UI_TextInput_Area'

export const Router_UI_TextPicker = 'pages/ui/UI_TextPicker'

export const Router_UI_TextTimer = 'pages/ui/UI_TextTimer'

export const Router_UI_TimePicker = 'pages/ui/UI_TimePicker'

export const Router_UI_Toggle = 'pages/ui/UI_Toggle'

export const Router_UI_Select = 'pages/ui/UI_Select'